<?php
/**
 * @license Copyright 2011-2014 BitPay Inc., MIT License
 * @see https://github.com/bitpay/magento-plugin/blob/master/LICENSE
 */

/**
 * @see Bitpay_Core_Block_Form_Bitpay
 */
 
$_code = $block->getMethodCode();
$bitpayScope = \Magento\Framework\App\ObjectManager::getInstance()->get('\Magento\Framework\App\Config\ScopeConfigInterface');
if ($bitpayScope->getValue('payment/bitpay/fullscreen')) {
	echo '<ul class="form-list" id="payment_form_' . $_code . '" style="display:none;">' .
	         '<li>You will be transfered to <a href="https://bitpay.com" target="_blank">BitPay</a> to complete your purchase when using this payment method.</li>' .
	     '</ul>';
}
?>
